# Generated by Django 3.2.18 on 2023-05-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_genres_id_movie_genre_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_ids',
        ),
    ]
