# Generated by Django 3.2.18 on 2023-05-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20230518_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_ids',
            field=models.TextField(blank=True),
        ),
    ]
