# Generated by Django 3.2.18 on 2023-05-21 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.DateTimeField(blank=True)),
                ('poster_path', models.TextField(blank=True)),
                ('backdrop_path', models.TextField(blank=True)),
                ('vote_count', models.IntegerField(blank=True)),
                ('vote_average', models.FloatField(blank=True)),
                ('popularity', models.FloatField(blank=True)),
                ('video', models.BooleanField(blank=True)),
                ('genre_ids', models.TextField(blank=True)),
                ('video_id', models.TextField(blank=True)),
                ('basket_users', models.ManyToManyField(related_name='basket_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('like_users', models.ManyToManyField(related_name='like_comments', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
